#####TRAINING ARGUMENTS

LOGS_INTERVAL = 500
SAVE_MODEL_DIRECTORY = './model_epoch_checkpoints'
TRAINING_DATA_DIRECTORY = './dataset/VCTK-CONVERTED/'

#####EVALUATION ARGUMENTS

EVALUATION_MODEL_PATH = './best_model_epoch/ckpt_80'
EVALUATION_TEST_DIRECTORY = './dataset/VCTK-DEMAND/test'
EVALUATION_SAVE_GENERATED_TRACKS_FLAG = True
EVALUATION_SAVE_GENERATED_TRACKS_DIRECTORY = './saved_tracks_best'