
#############GENERATOR CONSTANTS

TIME_CONFORMER_HEADS = 4
TIME_CONFORMER_CONV_KERNEL_SIZE = 31
TIME_CONFORMER_ATTENTION_DROPOUT = 0.2
TIME_FEED_FORWARD_DROPOUT = 0.2

#############CONFORMER CONSTANTS

CONFORMER_DIMENSION_HEADS = 64
CONFORMER_HEADS=8
CONFORMER_FEED_FORWARD_MULTIPLIER = 4
CONFORMER_CONV_EXPANSION_FACTOR = 2
CONFORMER_CONV_KERNEL_SIZE = 31
CONFORMER_ATTENTION_DROPOUT = 0.0
CONFORMER_FEED_FORWARD_DROPOUT = 0.0
CONFORMER_CONV_DROPOUT = 0
CONFORMER_CON_CAUSAL_ENABLED_FLAG = False
CONFORMER_CON_CAUSAL_DEFAULT_FLAG = False
CONFORMER_FREQUENCY_REARRANGEMENT = "b n c -> b c n"
CONFORMER_TIME_REARRANGEMENT = "b c n -> b n c"


#############DISCRIMINATOR CONSTANTS

DISCRIMINATOR_DROPOUT_RATE = 0.3
DISCRIMINATOR_DEPTH_OF_FEATURE_MAPS = 16

#############EVALUATION CONSTANTS

